local ErrorCodes = {}

ErrorCodes.MISSING_UUID = "DRX_E001"
ErrorCodes.DUPLICATE_UUID = "DRX_E002"
ErrorCodes.INVALID_INSTANCE_JSON = "DRX_E003"
ErrorCodes.CLASS_MISMATCH = "DRX_E004"
ErrorCodes.PATH_CLASH = "DRX_E005"
ErrorCodes.BRIDGE_CONNECT_FAILED = "DRX_E006"
ErrorCodes.BRIDGE_TIMEOUT = "DRX_E007"
ErrorCodes.EXPORT_FAILED = "DRX_E008"
ErrorCodes.IMPORT_FAILED = "DRX_E009"
ErrorCodes.CACHE_CORRUPTED = "DRX_E010"
ErrorCodes.UNSUPPORTED_PROPERTY = "DRX_E011"
ErrorCodes.INVALID_PAYLOAD = "DRX_E012"
ErrorCodes.FILESYSTEM_ERROR = "DRX_E013"
ErrorCodes.VALIDATION_FAILED = "DRX_E014"

ErrorCodes.DUPLICATE_UUID_REWRITE = "DRX_W001"
ErrorCodes.PROPERTY_SKIPPED = "DRX_W002"

ErrorCodes.ANCESTOR_INCLUDED = "DRX_I001"

return ErrorCodes
